baseURL: https://hugo-apero-docs.netlify.app/
languageCode: en
theme: hugo-apero
title: Hugo Apéro
author: Alison Hill
copyright: ''
googleAnalytics: ''
disqusShortname: ''
metaDataFormat: yaml
footnoteReturnLinkContents: '&#8617;'
paginate: 5
preserveTaxonomyNames: yes
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
enableEmoji: yes
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      hardwraps: no
      unsafe: yes
  highlight:
    style: github
  tableOfContents:
    endLevel: 2
    ordered: no
    startLevel: 2
params:
  custom_theme: ''
  customheadingFontFamily: Fraunces
  customtextFontFamily: Commissioner
  description: A modern, beautiful, and easily configurable blog theme for Hugo.
  favicon: /img/favicon.ico
  headingFontFamily: sans-serif
  logo: /img/blogophonic-mark-dark.png
  mainSections:
    - blog
    - project
    - talk
  navallcaps: yes
  orgLocal: Anywhere
  orgName: RStudio
  sharing_image: /img/papillons.jpg
  social:
    - icon: twitter
      icon_pack: fab
      url: https://twitter.com/kierisi
    - icon: youtube
      icon_pack: fab
      url: https://www.youtube.com/channel/UCE2WK5bvNtDblu4NO9PGtJA
    - icon: twitch
      icon_pack: fab
      url: https://www.twitch.tv/kierisi  
    - icon: github
      icon_pack: fab
      url: https://github.com/kierisi
    # - icon: address-card
    #   icon_pack: fas
    #   url: https://hugo-apero.netlify.app/
  socialInFooter: yes
  socialInHeader: no
  textFontFamily: sans-serif
  theme: sky
  twitter: kierisi
  utterances:
    issue_term: pathname
    label: 'comments :crystal_ball:'
    repo_name: hugo-apero/apero
    theme: boxy-light
    use_utterances: yes
taxonomies:
  category: categories
  series: series
  tag: tags
menu:
  footer:
    - name: License
      title: License
      url: /license/
      weight: 1
    - name: Contact
      title: Contact form
      url: /contact/
      weight: 2
    # - name: Contributors
    #   title: Contributors
    #   url: /contributors/
    #   weight: 3
  header:
    - name: About
      title: About Apéro
      url: /about/
      weight: 1
    - name: Blog
      title: Blog
      url: /blog/
      weight: 2
    - name: Projects
      title: Project Portfolio
      url: /project/
      weight: 3
    - name: Talks
      title: Talks
      url: /talk/
      weight: 4
    # - name: Elements
    #   title: Element Page
    #   url: /elements/
    #   weight: 6
privacy:
  disqus:
    disable: no
  googleAnalytics:
    anonymizeIP: yes
    disable: no
    respectDoNotTrack: yes
  instagram:
    disable: no
    simple: yes
  twitter:
    disable: no
    enableDNT: yes
    simple: no
  vimeo:
    disable: no
    enableDNT: yes
    simple: yes
  youtube:
    disable: no
    privacyEnhanced: yes
